ptf #
MODEL INPUT FILE
d_var1,#dvar1          #
d_var2,#dvar2          #
d_var3,#dvar3          #
d_var4,#dvar4          #
d_var5,#dvar5          #
d_var6,#dvar6          #
d_var7,#dvar7          #
d_var8,#dvar8          #
d_var9,#dvar9          #
d_var10,#dvar10          #
par1,#par1          #
par2,#par2          #
par3,#par3          #
par4,#par4          #
par5,#par5          #
par6,#par6          #
par7,#par7          #
par8,#par8          #
par9,#par9          #
par10,#par10          #
